server:
  port: 8100

spring:
  application:
    name: cgm-starter
  datasource:
    url: jdbc:mysql://47.100.137.154:3306/starter?serverTimezone=Asia/Shanghai
    hikari:
      username: starter
      password: 0Starter8
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  messages:
    basename: messages/messages
    encoding: utf-8
    use-code-as-default-message: true
  servlet:
    multipart:
      max-file-size: 20480MB
      max-request-size: 20480MB

logging:
  level:
    com.cgm.tools.account: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true

extra:
  default-avatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif
  # 此处app_key为百度demo提供，请填写网页上申请的app_key
  baidu-app-key: 4E1BG9lTnlSeIf1NQFlrSq6h
  # 此处app_secret为百度demo提供，请填写网页上申请的app_secret
  baidu-secret-key: 544ca4657ba8002e3dea3ac2f5fdd241

